name: Sessions
on:
  workflow_dispatch:
    inputs:
      branch:
        default: 'testit'
        description: 'Default branch to generate'
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      TESTSPACE_CRED:
        required: true
env:
  TESTSPACE_CRED: ${{ secrets.TESTSPACE_CRED }}
  GHORG:          ${{ github.repository_owner }}
  REPO:           ${{ github.event.repository.name }}
  TS_FOLDER: armWorkflow

jobs:
  sessions:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$TS_FOLDER"
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.branch }}
      - run: npm install
      - name: RUN SESSIONS
        run: node run.sessions.js ${{ inputs.branch}} specs/allSessions.json